apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: hbla560ru-python 
  janus-idp.io/tekton: hbla560ru-python
  backstage.io/kubernetes-id: hbla560ru-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: hbla560ru-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  